### ISSUE TITLE
seek for help about kbp data

### ISSUE THREAD

**Issue by rainbow7xj** [rgabbard-bbn/kbp-2014-event-arguments#11]
could you plz give me a copy of kbp 2017 data? thanks.

**Comment by rainbow7xj** [comment]
my email: rainbow7xj@gmail.com

**Comment by heintzcode** [comment]
I believe you have to get that directly from LDC or NIST. It's not ours to give.

**Comment by rogerbock** [comment]
@heintzcode is correct.

> Access to TAC KBP 2017 data is restricted to registered TAC KBP 2017 participants who have submitted all the required User Agreement forms.

For more details, see https://tac.nist.gov/2017/KBP/data.html
